version: 0.1
OS: linux
files:
  - source: /
    destination: /home/ec2-user/project
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
  